[general]
# Exit directly after copy/save action
early-exit = true
# Select the tool on startup [possible values: pointer, crop, line, arrow, rectangle, text, marker, blur, brush]
initial-tool = "rectangle"
# Configure the command to be called on copy, for example `wl-copy`
copy-command = "wl-copy --type image/png"
# Increase or decrease the size of the annotations
#annotation-size-factor = 2
# Filename to use for saving action. Omit to disable saving to file. Might contain format specifiers: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
#output-filename = "/tmp/test-%Y-%m-%d_%H:%M:%S.png"
output-filename = "/home/jonathan/Pictures/Screenshots/%Y-%m-%d_%H-%M-%S.png"
# After copying the screenshot, save it to a file as well
save-after-copy = true
# Hide toolbars by default
default-hide-toolbars = false
# The primary highlighter to use, the other is accessible by holding CTRL at the start of a highlight [possible values: block, freehand]
primary-highlighter = "block"
disable-notifications = false

# Font to use for text annotations
[font]
family = "Roboto"
style = "Bold"

# custom colours for the colour palette
[color-palette]
palette = [
  "#dc143c",
  "#008000",
  "#a52a2a",
  "#ff1493",
  "#ffd700",
  "#00ffff"
]
